todos:
    name: todos
    path: /todos
    controller: MyCrm\Modules\LibertaTodos\Controllers\MainController::indexAction

todos_with_param:
    name: todos_with_param
    path: /todos/{slug}
    controller: MyCrm\Modules\LibertaTodos\Controllers\DynamicController::showAction