visualbuilder:
    name: visualbuilder
    path: /visualbuilder/see/{moduleId}
    controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::indexAction

test:
    name: test
    path: /test
    controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::testAction

load_editor_file:
  name: load_editor_file
  path: /visualbuilder/load_editor_file
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::loadEditorFileAjax
  requirements:
    _method: POST

load_select_component:
  name: load_select_component
  path: /visualbuilder/load_select_component
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::loadSelectComponentAjax
  requirements:
    _method: POST

load_datatable_component:
  name: load_datatable_component
  path: /visualbuilder/load_datatable_component
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::loadDatatableComponentAjax
  requirements:
    _method: POST

generate_form_ajax:
  name: generate_form_ajax
  path: /visualbuilder/generate_form_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::generateFormAjax
  requirements:
    _method: POST

generate_table_ajax:
  name: generate_table_ajax
  path: /visualbuilder/generate_table_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::generateTableAjax
  requirements:
    _method: POST

create_xml_bindings_ajax:
  name: create_xml_bindings_ajax
  path: /visualbuilder/create_xml_bindings_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::createFormXmlBindingsAjax
  requirements:
    _method: POST

remove_component_ajax:
  name: remove_component_ajax
  path: /visualbuilder/remove_component_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::removeComponentAjax
  requirements:
    _method: POST

create_new_form_file_ajax:
  name: create_new_form_file_ajax
  path: /visualbuilder/create_new_form_file_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::createNewFormAjax
  requirements:
    _method: POST

update_form_file_ajax:
  name: update_form_file_ajax
  path: /visualbuilder/update_form_file_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::updateFormAjax
  requirements:
    _method: POST

save_clean_file_ajax:
  name: save_clean_file_ajax
  path: /visualbuilder/save_clean_file_ajax
  controller: MyCrm\Modules\MyCrmVisualBuilder\Controllers\MainController::saveCleanAjaxAction
  requirements:
    _method: POST