querybuilder:
    name: querybuilder
    path: /querybuilder/see/{moduleId}
    controller: MyCrm\Modules\LibertaQueryBuilder\Controllers\MainController::indexAction

# Ajax routes
update_query:
    name: update_query
    path: /querybuilder/update_query
    controller: MyCrm\Modules\LibertaQueryBuilder\Controllers\MainController::updateQueryAjax


add_query:
    name: add_query
    path: /querybuilder/add_query
    controller: MyCrm\Modules\LibertaQueryBuilder\Controllers\MainController::addQueryAjax

delete_query:
    name: delete_query
    path: /querybuilder/delete_query
    controller: MyCrm\Modules\LibertaQueryBuilder\Controllers\MainController::deleteQueryAjax