users:
    name: users
    path: /users
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::indexAction

create_group:
    name: create_group
    path: /users/create_group
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::createGroupAction

create_user:
    name: create_user
    path: /users/create_user
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::createUserAction

edit_user:
    name: edit_user
    path: /users/edit_user/{userId}
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::editUserAction

edit_group:
    name: edit_group
    path: /users/edit_group/{groupId}
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::editGroupAction

# Ajax
delete_user:
    name: delete_user
    path: /users/delete_user_ajax
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::deleteUserAjax

insert_group:
    name: insert_group
    path: /users/insert_group_ajax
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::insertGroupAjax

insert_user:
    name: insert_user
    path: /users/insert_user_ajax
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::insertUserAjax

update_user:
    name: update_user
    path: /users/update_user_ajax
    controller: MyCrm\Modules\MyCrmUsers\Controllers\MainController::updateUserAjax
