/tickets:
    name: /tickets
    path: /tickets
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::indexAction

/open_case:
    name: /open_case
    path: /tickets/open_case
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::openCaseAction

/view_case:
    name: /view_case
    path: /tickets/view_case/{id}
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::viewCaseAction

/edit_case:
    name: /edit_case
    path: /tickets/edit_case/{id}
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::editCaseAction

# Ajax
/delete_case_ajax:
    name: /delete_case_ajax
    path: /tickets/delete_case_ajax
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::deleteCaseAjax

/get_contacts_account_ajax:
    name: /get_contacts_account_ajax
    path: /tickets/get_contacts_account_ajax
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::getContactForAccountAjax

/insert_case_ajax:
    name: /insert_case_ajax
    path: /tickets/insert_case_ajax
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::insertCaseAjax

/update_case_ajax:
    name: /update_case_ajax
    path: /tickets/update_case_ajax
    controller: MyCrm\Modules\MyCrmTickets\Controllers\MainController::updateCaseAjax