querybuilder:
    name: querybuilder
    path: /querybuilder
    controller: MyCrm\Modules\MyCrmQueryBuilder\Controllers\MainController::indexAction

entity_table:
    name: entity_table
    path: /querybuilder/entity_table
    controller: MyCrm\Modules\MyCrmQueryBuilder\Controllers\MainController::entityTableAction
